### ISSUE TITLE
[BE] 기록 썸네일 이미지 필드 추가

### ISSUE THREAD

**Issue by dgnppr** [travel-record/backend#1]
# ☑️ 진행할 작업

기록 썸네일 이미지 필드 추가

# 📝 TODO

- [x] DB record table에 이미지 필드 추가
- [x] JPA record entity에 이미지 필드 추가
- [x] JPA record entity 요청/수정/조회에 이미지 필드 추가
- [x] API Docs update

# ⚙️ 기타
