### ISSUE TITLE
[BE] 좋아요 알림 생성

### ISSUE THREAD

**Issue by dgnppr** [travel-record/backend#13]
# ☑️ 진행할 작업

기록에 좋아요를 하면 기록 작성자을 향한 알림이 생성된다
알림 조회 시 알림 타입에 따른 content 변경

# 📝 TODO

- [x] 알림 생성 구현
- [x] 알림 content 동적 변경 
- [x] 알림 리스트 조회 reponse 필드 추가 
- [x] 테스트 코드

# ⚙️ 기타

# 이슈

### 비동기 테스트에서 테스트 실패

@Transactional + @Async 서비스 메서드를 호출하였을 때, 호출한 메서드에도 트랜잭션 처리가 되어있을 때,
호출한 메서드의 트랜잭션에서 insert한 엔티티를 비동기 메서드에서 사용할 때, 외래키 제약 조건 위반하는 문제 발생
