### ISSUE TITLE
[BE] 기록에 등록된 댓글 리스트 조회 API

### ISSUE THREAD

**Issue by dgnppr** [travel-record/backend#18]
# 작업

기록에 등록된 댓글 리스트 조회 기능 구현
기록 단건 조회 response 필드 수정

# TODO

- [x] 기록에 등록된 댓글 리스트 조회 controller 구현
- [x] 기록에 등록된 댓글 리스트 조회 테스트
- [x] 기록 단건 조회 response 필드 수정 후 테스트

# 기타
