### ISSUE TITLE
[BE] 기록 순서 변경 구현

### ISSUE THREAD

**Issue by dgnppr** [travel-record/backend#26]
# ☑️ 진행할 작업

기록 순서 변경 로직 구현

# 📝 TODO
- [x] 기록 순서 필드 추가
- [x] 순서 동기화 로직 구현
- [x] 기록 순서 변경 API
- [x] 테스트
- [x] 문서 작성

# ⚙️ 기타
