### ISSUE TITLE
[BE] API Response 수정

### ISSUE THREAD

**Issue by dgnppr** [travel-record/backend#35]
# ☑️ 진행할 작업
create, delte api response data 필드 경량화

# 📝 TODO

- [x] ApiResponse static 메서드 생성
- [x] CustomException message 필드 추가
- [x] user create, delete api response 수정
- [x] feed create, delete api response 수정
- [x] record create, delete api response 수정
- [x] comment create, delete api response 수정
- [x] 문서 수정
 
# ⚙️ 기타
