### ISSUE TITLE
[BE] Authentication 리팩토링

### ISSUE THREAD

**Issue by dgnppr** [travel-record/backend#36]
# ☑️ 진행할 작업

- Spring Security Filter refactoring
- Authentication uses refactoring

# 📝 TODO

- [x] spring security 리팩토링
- [x] Controller Authentication 리팩토링
- [x] UserEntity safe casting
- [x] Controller test code 리팩토링

# ⚙️ 기타
