### ISSUE TITLE
[BE] 사용자 초대하기

### ISSUE THREAD

**Issue by dgnppr** [travel-record/backend#58]
# TODO
초대 기능 구현

# 작업 리스트

- [x] 초대 엔티티 생성
- [x] 매니저 엔티티 생성
- [x] 초대 기능 구현
- [x] 알림 전송
- [x] 테스트
- [x] 문서화

# ETC
