### ISSUE TITLE
[BE] 사용자 기록에 좋아요 등록/해제

### ISSUE THREAD

**Issue by dgnppr** [travel-record/backend#6]
# ☑️ 진행할 작업

사용자 기록에 좋아요 등록/해제 기능을 추가한다
기록 관련 API 필드에 좋아요 필드를 추가한다
전반적인 리팩토링을 진행한다

# 📝 TODO

- [x] MySQL 테이블 생성
- [x] 엔티티 매핑
- [x] API 생성
- [x] 기록 조회 API에 liked 필드 추가
- [x] 문서 작성
- [x] 리팩토링(댓글 조회 시 기록 내용 제외)

# ⚙️ 기타
